const allQuestions = [
  // ==================== NIVEL A1 ====================
  // Sección: Verbo To Be
  {
    question: "I ________ the painter. (Affirmative)",
    type: "fill",
    answer: "am",
    acceptAlso: ["am"],
    category: "grammar",
    level: "A1",
    section: "Verbo To Be",
    points: 1,
    order: 1,
  },
  {
    question: "The tools ________ in the truck. (Negative)",
    type: "fill",
    answer: "are not",
    acceptAlso: ["aren't", "arent"],
    category: "grammar",
    level: "A1",
    section: "Verbo To Be",
    points: 1,
    order: 2,
  },
  {
    question: "She ________ the manager. (Affirmative)",
    type: "fill",
    answer: "is",
    acceptAlso: ["is"],
    category: "grammar",
    level: "A1",
    section: "Verbo To Be",
    points: 1,
    order: 3,
  },
  {
    question: "We ________ ready for the job. (Negative)",
    type: "fill",
    answer: "are not",
    acceptAlso: ["aren't", "arent"],
    category: "grammar",
    level: "A1",
    section: "Verbo To Be",
    points: 1,
    order: 4,
  },
  {
    question: "It ________ a new drill. (Affirmative)",
    type: "fill",
    answer: "is",
    acceptAlso: ["is"],
    category: "grammar",
    level: "A1",
    section: "Verbo To Be",
    points: 1,
    order: 5,
  },

  // Sección: Adjetivos Posesivos
  {
    question: "I have a helmet. ________ helmet is yellow.",
    type: "fill",
    answer: "My",
    acceptAlso: ["my"],
    category: "grammar",
    level: "A1",
    section: "Adjetivos Posesivos",
    points: 1,
    order: 1,
  },
  {
    question: "John has a truck. ________ truck is white.",
    type: "fill",
    answer: "His",
    acceptAlso: ["his"],
    category: "grammar",
    level: "A1",
    section: "Adjetivos Posesivos",
    points: 1,
    order: 2,
  },
  {
    question: "Maria has an office. ________ office is big.",
    type: "fill",
    answer: "Her",
    acceptAlso: ["her"],
    category: "grammar",
    level: "A1",
    section: "Adjetivos Posesivos",
    points: 1,
    order: 3,
  },
  {
    question: "We have a team. ________ team is professional.",
    type: "fill",
    answer: "Our",
    acceptAlso: ["our"],
    category: "grammar",
    level: "A1",
    section: "Adjetivos Posesivos",
    points: 1,
    order: 4,
  },
  {
    question: "You have a permit. Where is ________ permit?",
    type: "fill",
    answer: "your",
    acceptAlso: ["your"],
    category: "grammar",
    level: "A1",
    section: "Adjetivos Posesivos",
    points: 1,
    order: 5,
  },

  // Sección: There is/are
  {
    question: "________________ forklift in the warehouse.",
    type: "fill",
    answer: "There is a",
    acceptAlso: ["There is an", "There is"],
    category: "grammar",
    level: "A1",
    section: "There is/are",
    points: 1,
    order: 1,
  },
  {
    question: "________________ 50 bricks in the patio.",
    type: "fill",
    answer: "There are",
    acceptAlso: ["There are"],
    category: "grammar",
    level: "A1",
    section: "There is/are",
    points: 1,
    order: 2,
  },
  {
    question: "________________ emergency exit near the stairs.",
    type: "fill",
    answer: "There is an",
    acceptAlso: ["There is a", "There is"],
    category: "grammar",
    level: "A1",
    section: "There is/are",
    points: 1,
    order: 3,
  },
  {
    question: "________________ many workers in the building.",
    type: "fill",
    answer: "There are",
    acceptAlso: ["There are"],
    category: "grammar",
    level: "A1",
    section: "There is/are",
    points: 1,
    order: 4,
  },
  {
    question: "________________ extension cord in the box.",
    type: "fill",
    answer: "There is an",
    acceptAlso: ["There is a", "There is"],
    category: "grammar",
    level: "A1",
    section: "There is/are",
    points: 1,
    order: 5,
  },

  // Sección: Preposiciones de Lugar
  {
    question: "The keys are ________ the table. (Sobre)",
    type: "multiple",
    options: ["in", "on", "under", "next to"],
    answer: "1",
    category: "grammar",
    level: "A1",
    section: "Preposiciones",
    points: 1,
    order: 1,
  },
  {
    question: "The hammer is ________ the toolbox. (Dentro)",
    type: "multiple",
    options: ["in", "on", "under", "next to"],
    answer: "0",
    category: "grammar",
    level: "A1",
    section: "Preposiciones",
    points: 1,
    order: 2,
  },
  {
    question: "The supervisor is ________ the truck. (Al lado)",
    type: "multiple",
    options: ["in", "on", "under", "next to"],
    answer: "3",
    category: "grammar",
    level: "A1",
    section: "Preposiciones",
    points: 1,
    order: 3,
  },
  {
    question: "The cables are ________ the floor. (Debajo de)",
    type: "multiple",
    options: ["in", "on", "under", "next to"],
    answer: "2",
    category: "grammar",
    level: "A1",
    section: "Preposiciones",
    points: 1,
    order: 4,
  },

  // Sección: Adverbios de Frecuencia
  {
    question: "(Always / I / wear / gloves) Ordena:",
    type: "fill",
    answer: "I always wear gloves",
    acceptAlso: ["I always wear gloves."],
    category: "grammar",
    level: "A1",
    section: "Adverbios de Frecuencia",
    points: 1,
    order: 1,
  },
  {
    question: "(is / late / He / never) Ordena:",
    type: "fill",
    answer: "He is never late",
    acceptAlso: ["He is never late."],
    category: "grammar",
    level: "A1",
    section: "Adverbios de Frecuencia",
    points: 1,
    order: 2,
  },
  {
    question: "(check / We / sometimes / the oil) Ordena:",
    type: "fill",
    answer: "We sometimes check the oil",
    acceptAlso: ["We sometimes check the oil."],
    category: "grammar",
    level: "A1",
    section: "Adverbios de Frecuencia",
    points: 1,
    order: 3,
  },

  // Sección: Can/Can't
  {
    question: "Yo puedo usar el taladro (Traduce):",
    type: "fill",
    answer: "I can use the drill",
    acceptAlso: ["I can use the drill."],
    category: "grammar",
    level: "A1",
    section: "Can/Can't",
    points: 2,
    order: 1,
  },
  {
    question: "Ella no puede conducir el camión (Traduce):",
    type: "fill",
    answer: "She cannot drive the truck",
    acceptAlso: ["She can't drive the truck", "She cant drive the truck"],
    category: "grammar",
    level: "A1",
    section: "Can/Can't",
    points: 2,
    order: 2,
  },
  {
    question: "¿Puedes ayudarme? (Traduce):",
    type: "fill",
    answer: "Can you help me?",
    acceptAlso: ["Can you help me"],
    category: "grammar",
    level: "A1",
    section: "Can/Can't",
    points: 2,
    order: 3,
  },
  {
    question: "Nosotros podemos empezar ahora (Traduce):",
    type: "fill",
    answer: "We can start now",
    acceptAlso: ["We can start now."],
    category: "grammar",
    level: "A1",
    section: "Can/Can't",
    points: 2,
    order: 4,
  },

  // Sección: How much / How many
  {
    question: "________ ________ sand do we need?",
    type: "fill",
    answer: "How much",
    acceptAlso: ["How much"],
    category: "grammar",
    level: "A1",
    section: "How much/many",
    points: 1,
    order: 1,
  },
  {
    question: "________ ________ screws are in the box?",
    type: "fill",
    answer: "How many",
    acceptAlso: ["How many"],
    category: "grammar",
    level: "A1",
    section: "How much/many",
    points: 1,
    order: 2,
  },
  {
    question: "________ ________ gallons of paint do you want?",
    type: "fill",
    answer: "How many",
    acceptAlso: ["How many"],
    category: "grammar",
    level: "A1",
    section: "How much/many",
    points: 1,
    order: 3,
  },
  {
    question: "________ ________ money is the total?",
    type: "fill",
    answer: "How much",
    acceptAlso: ["How much"],
    category: "grammar",
    level: "A1",
    section: "How much/many",
    points: 1,
    order: 4,
  },

  // Sección: Present Continuous
  {
    question: "I (work) ________________ in the roof.",
    type: "fill",
    answer: "am working",
    acceptAlso: ["am working"],
    category: "grammar",
    level: "A1",
    section: "Present Continuous",
    points: 1,
    order: 1,
  },
  {
    question: "They (not / clean) ________________ the kitchen.",
    type: "fill",
    answer: "are not cleaning",
    acceptAlso: ["aren't cleaning", "arent cleaning"],
    category: "grammar",
    level: "A1",
    section: "Present Continuous",
    points: 1,
    order: 2,
  },
  {
    question: "Is he (repair) ________________ the AC?",
    type: "fill",
    answer: "repairing",
    acceptAlso: ["repairing"],
    category: "grammar",
    level: "A1",
    section: "Present Continuous",
    points: 1,
    order: 3,
  },
  {
    question: "We (drive) ________________ to the job site.",
    type: "fill",
    answer: "are driving",
    acceptAlso: ["are driving"],
    category: "grammar",
    level: "A1",
    section: "Present Continuous",
    points: 1,
    order: 4,
  },

  // Sección: Pasado Simple Was/Were
  {
    question: "I ________ at the office yesterday.",
    type: "fill",
    answer: "was",
    acceptAlso: ["was"],
    category: "grammar",
    level: "A1",
    section: "Past Simple Was/Were",
    points: 1,
    order: 1,
  },
  {
    question: "The materials ________ not ready.",
    type: "fill",
    answer: "were",
    acceptAlso: ["were"],
    category: "grammar",
    level: "A1",
    section: "Past Simple Was/Were",
    points: 1,
    order: 2,
  },
  {
    question: "Where ________ you at 10:00 AM?",
    type: "fill",
    answer: "were",
    acceptAlso: ["were"],
    category: "grammar",
    level: "A1",
    section: "Past Simple Was/Were",
    points: 1,
    order: 3,
  },
  {
    question: "The project ________ very difficult.",
    type: "fill",
    answer: "was",
    acceptAlso: ["was"],
    category: "grammar",
    level: "A1",
    section: "Past Simple Was/Were",
    points: 1,
    order: 4,
  },

  // Sección: Verbos Regulares -ed
  {
    question: "Yesterday I ____________ the door. (fix)",
    type: "fill",
    answer: "fixed",
    acceptAlso: ["fixed"],
    category: "grammar",
    level: "A1",
    section: "Verbos Regulares",
    points: 1,
    order: 1,
  },
  {
    question: "Yesterday we ____________ the wall. (finish)",
    type: "fill",
    answer: "finished",
    acceptAlso: ["finished"],
    category: "grammar",
    level: "A1",
    section: "Verbos Regulares",
    points: 1,
    order: 2,
  },
  {
    question: "Yesterday she ____________ the client. (call)",
    type: "fill",
    answer: "called",
    acceptAlso: ["called"],
    category: "grammar",
    level: "A1",
    section: "Verbos Regulares",
    points: 1,
    order: 3,
  },

  // Sección: Reading A1
  {
    question: 'DAILY REPORT: "Yesterday was Monday. I arrived at the job site at 7:30 AM..." The worker arrived at 8:00 AM.',
    type: "multiple",
    options: ["True", "False"],
    answer: "1",
    category: "reading",
    level: "A1",
    section: "Reading A1",
    points: 2,
    order: 1,
  },
  {
    question: "Mr. Smith is the supervisor.",
    type: "multiple",
    options: ["True", "False"],
    answer: "0",
    category: "reading",
    level: "A1",
    section: "Reading A1",
    points: 2,
    order: 2,
  },
  {
    question: "They repaired a fence.",
    type: "multiple",
    options: ["True", "False"],
    answer: "0",
    category: "reading",
    level: "A1",
    section: "Reading A1",
    points: 2,
    order: 3,
  },
  {
    question: "There were 5 helpers.",
    type: "multiple",
    options: ["True", "False"],
    answer: "1",
    category: "reading",
    level: "A1",
    section: "Reading A1",
    points: 2,
    order: 4,
  },
  {
    question: "The crane was working perfectly.",
    type: "multiple",
    options: ["True", "False"],
    answer: "1",
    category: "reading",
    level: "A1",
    section: "Reading A1",
    points: 2,
    order: 5,
  },

  // ==================== NIVEL A2 ====================
  // Sección: Present Simple vs Continuous
  {
    question: "I (work / am working) ________________ right now, call me later.",
    type: "multiple",
    options: ["work", "am working"],
    answer: "1",
    category: "grammar",
    level: "A2",
    section: "Present Simple vs Continuous",
    points: 1,
    order: 1,
  },
  {
    question: "He (drives / is driving) ________________ the truck every Monday.",
    type: "multiple",
    options: ["drives", "is driving"],
    answer: "0",
    category: "grammar",
    level: "A2",
    section: "Present Simple vs Continuous",
    points: 1,
    order: 2,
  },
  {
    question: "Look! The supervisor (comes / is coming) ________________ to the site.",
    type: "multiple",
    options: ["comes", "is coming"],
    answer: "1",
    category: "grammar",
    level: "A2",
    section: "Present Simple vs Continuous",
    points: 1,
    order: 3,
  },
  {
    question: "We usually (clean / are cleaning) ________________ the tools at 5:00 PM.",
    type: "multiple",
    options: ["clean", "are cleaning"],
    answer: "0",
    category: "grammar",
    level: "A2",
    section: "Present Simple vs Continuous",
    points: 1,
    order: 4,
  },
  {
    question: "They (repair / are repairing) ________________ the roof at this moment.",
    type: "multiple",
    options: ["repair", "are repairing"],
    answer: "1",
    category: "grammar",
    level: "A2",
    section: "Present Simple vs Continuous",
    points: 1,
    order: 5,
  },

  // Sección: Live Reports
  {
    question: '"No puedo hablar, estoy instalando los cables" (Traduce):',
    type: "fill",
    answer: "I cannot talk, I am installing the cables",
    acceptAlso: [
      "I can't talk, I'm installing the cables",
      "I cant talk, I am installing the cables",
    ],
    category: "writing",
    level: "A2",
    section: "Live Reports",
    points: 2,
    order: 1,
  },
  {
    question: '"¿Qué está haciendo el equipo ahora?" (Traduce):',
    type: "fill",
    answer: "What is the team doing now?",
    acceptAlso: ["What are the team doing now?"],
    category: "writing",
    level: "A2",
    section: "Live Reports",
    points: 2,
    order: 2,
  },
  {
    question: '"Ellos no están usando el casco" (Traduce):',
    type: "fill",
    answer: "They are not using the helmet",
    acceptAlso: [
      "They aren't using the helmet",
      "They are not wearing the helmet",
    ],
    category: "writing",
    level: "A2",
    section: "Live Reports",
    points: 2,
    order: 3,
  },

  // Sección: Comparativos
  {
    question: "Steel is ________________ (strong) than aluminum.",
    type: "fill",
    answer: "stronger",
    acceptAlso: ["stronger"],
    category: "grammar",
    level: "A2",
    section: "Comparativos",
    points: 1,
    order: 1,
  },
  {
    question: "This project is ________________ (expensive) than the last one.",
    type: "fill",
    answer: "more expensive",
    acceptAlso: ["more expensive"],
    category: "grammar",
    level: "A2",
    section: "Comparativos",
    points: 1,
    order: 2,
  },
  {
    question: "The new ladder is ________________ (safe) than the old one.",
    type: "fill",
    answer: "safer",
    acceptAlso: ["safer"],
    category: "grammar",
    level: "A2",
    section: "Comparativos",
    points: 1,
    order: 3,
  },
  {
    question: "Working in the morning is ________________ (good) than the night shift.",
    type: "fill",
    answer: "better",
    acceptAlso: ["better"],
    category: "grammar",
    level: "A2",
    section: "Comparativos",
    points: 1,
    order: 4,
  },

  // Sección: Superlativos
  {
    question: "This is the ________________ (important) safety rule.",
    type: "fill",
    answer: "most important",
    acceptAlso: ["most important"],
    category: "grammar",
    level: "A2",
    section: "Superlativos",
    points: 1,
    order: 1,
  },
  {
    question: "He is the ________________ (fast) painter in the company.",
    type: "fill",
    answer: "fastest",
    acceptAlso: ["fastest"],
    category: "grammar",
    level: "A2",
    section: "Superlativos",
    points: 1,
    order: 2,
  },
  {
    question: "What is the ________________ (cheap) material in the store?",
    type: "fill",
    answer: "cheapest",
    acceptAlso: ["cheapest"],
    category: "grammar",
    level: "A2",
    section: "Superlativos",
    points: 1,
    order: 3,
  },
  {
    question: "This was the ________________ (difficult) task of the week.",
    type: "fill",
    answer: "most difficult",
    acceptAlso: ["most difficult"],
    category: "grammar",
    level: "A2",
    section: "Superlativos",
    points: 1,
    order: 4,
  },

  // Sección: Verbos Irregulares
  {
    question: "Go -> ________ (Past)",
    type: "fill",
    answer: "went",
    acceptAlso: ["went"],
    category: "grammar",
    level: "A2",
    section: "Irregular Verbs",
    points: 1,
    order: 1,
  },
  {
    question: "Buy -> ________ (Past)",
    type: "fill",
    answer: "bought",
    acceptAlso: ["bought"],
    category: "grammar",
    level: "A2",
    section: "Irregular Verbs",
    points: 1,
    order: 2,
  },
  {
    question: "See -> ________ (Past)",
    type: "fill",
    answer: "saw",
    acceptAlso: ["saw"],
    category: "grammar",
    level: "A2",
    section: "Irregular Verbs",
    points: 1,
    order: 3,
  },
  {
    question: "Take -> ________ (Past)",
    type: "fill",
    answer: "took",
    acceptAlso: ["took"],
    category: "grammar",
    level: "A2",
    section: "Irregular Verbs",
    points: 1,
    order: 4,
  },
  {
    question: "Speak -> ________ (Past)",
    type: "fill",
    answer: "spoke",
    acceptAlso: ["spoke"],
    category: "grammar",
    level: "A2",
    section: "Irregular Verbs",
    points: 1,
    order: 5,
  },

  // Sección: Reading A2
  {
    question: "CASE: Floor options. Which option is better for a high-traffic area?",
    type: "multiple",
    options: ["Wood (Option A)", "Tile (Option B)"],
    answer: "1",
    category: "reading",
    level: "A2",
    section: "Reading A2",
    points: 3,
    order: 1,
  },
  {
    question: "Why is Option B better? (Reason 1):",
    type: "fill",
    answer: "easier to clean",
    acceptAlso: [
      "more durable",
      "stronger",
      "it is easier to clean",
      "it is stronger",
    ],
    category: "reading",
    level: "A2",
    section: "Reading A2",
    points: 2,
    order: 2,
  },
  {
    question: "If the client has a very small budget, which one?",
    type: "fill",
    answer: "Wood",
    acceptAlso: ["Option A", "wood"],
    category: "reading",
    level: "A2",
    section: "Reading A2",
    points: 1,
    order: 3,
  },

  // Sección: Commands
  {
    question: '"Gira a la izquierda en la señal de stop" (Traduce):',
    type: "fill",
    answer: "Turn left at the stop sign",
    acceptAlso: ["Turn left at the stop sign."],
    category: "writing",
    level: "A2",
    section: "Commands",
    points: 2,
    order: 1,
  },
  {
    question: '"Sube la escalera con cuidado" (Traduce):',
    type: "fill",
    answer: "Go up the ladder carefully",
    acceptAlso: ["Climb the ladder carefully"],
    category: "writing",
    level: "A2",
    section: "Commands",
    points: 2,
    order: 2,
  },
  {
    question: '"Pon las cajas detrás del camión" (Traduce):',
    type: "fill",
    answer: "Put the boxes behind the truck",
    acceptAlso: ["Put the boxes behind the truck."],
    category: "writing",
    level: "A2",
    section: "Commands",
    points: 2,
    order: 3,
  },

  // ==================== NIVEL B1 ====================
  // Sección: Present Perfect
  {
    question: "I ____________ (work) in construction for 10 years.",
    type: "fill",
    answer: "have worked",
    acceptAlso: ["have worked"],
    category: "grammar",
    level: "B1",
    section: "Present Perfect",
    points: 2,
    order: 1,
  },
  {
    question: "The company ____________ (buy) three new trucks this year.",
    type: "fill",
    answer: "has bought",
    acceptAlso: ["has bought"],
    category: "grammar",
    level: "B1",
    section: "Present Perfect",
    points: 2,
    order: 2,
  },
  {
    question: "____________ you ____________ (see) the new safety regulations?",
    type: "fill",
    answer: "Have seen",
    acceptAlso: ["Have you seen"],
    category: "grammar",
    level: "B1",
    section: "Present Perfect",
    points: 2,
    order: 3,
  },
  {
    question: "We ____________ not ____________ (finish) the inspection yet.",
    type: "fill",
    answer: "have finished",
    acceptAlso: ["have not finished"],
    category: "grammar",
    level: "B1",
    section: "Present Perfect",
    points: 2,
    order: 4,
  },
  {
    question: "He ____________ (be) the supervisor since January.",
    type: "fill",
    answer: "has been",
    acceptAlso: ["has been"],
    category: "grammar",
    level: "B1",
    section: "Present Perfect",
    points: 2,
    order: 5,
  },

  // Sección: For vs Since
  {
    question: "I have lived in the US ________ 2015.",
    type: "multiple",
    options: ["for", "since"],
    answer: "1",
    category: "grammar",
    level: "B1",
    section: "For vs Since",
    points: 1,
    order: 1,
  },
  {
    question: "We have used this machine ________ six months.",
    type: "multiple",
    options: ["for", "since"],
    answer: "0",
    category: "grammar",
    level: "B1",
    section: "For vs Since",
    points: 1,
    order: 2,
  },

  // Sección: Modals
  {
    question: "You __________ wear a harness when working on the roof. (Obligación fuerte)",
    type: "multiple",
    options: ["must", "should", "can't"],
    answer: "0",
    category: "grammar",
    level: "B1",
    section: "Modals",
    points: 1,
    order: 1,
  },
  {
    question: "You __________ use this tool; it is broken. (Prohibición)",
    type: "multiple",
    options: ["must", "should", "can't"],
    answer: "2",
    category: "grammar",
    level: "B1",
    section: "Modals",
    points: 1,
    order: 2,
  },
  {
    question: "I think we __________ buy more cement today. (Recomendación)",
    type: "multiple",
    options: ["must", "should", "can't"],
    answer: "1",
    category: "grammar",
    level: "B1",
    section: "Modals",
    points: 1,
    order: 3,
  },

  // Sección: Will vs Going to
  {
    question: "Next Monday, we ________________ (start) the new project. (Plan)",
    type: "fill",
    answer: "are going to start",
    acceptAlso: ["are going to start"],
    category: "grammar",
    level: "B1",
    section: "Will vs Going to",
    points: 2,
    order: 1,
  },
  {
    question: "Don't worry, I ________________ (call) the client right now. (Promesa)",
    type: "fill",
    answer: "will call",
    acceptAlso: ["will call"],
    category: "grammar",
    level: "B1",
    section: "Will vs Going to",
    points: 2,
    order: 2,
  },

  // Sección: First Conditional
  {
    question: "If we ________ (finish) early, we ________ (go) home at 3:00.",
    type: "fill",
    answer: "finish will go",
    acceptAlso: ["finish, will go"],
    category: "grammar",
    level: "B1",
    section: "First Conditional",
    points: 3,
    order: 1,
  },

  // Sección: Reading B1
  {
    question: "EMAIL: ¿Cuál es la queja principal del cliente?",
    type: "fill",
    answer: "the roof is not finished",
    acceptAlso: [
      "progress is slow",
      "the roof is not done",
      "lack of progress",
    ],
    category: "reading",
    level: "B1",
    section: "Reading B1",
    points: 3,
    order: 1,
  },

  // ==================== NIVEL B2 ====================
  // Sección: Passive Voice
  {
    question: "The inspector approved the permits. (Passive): The permits ________________.",
    type: "fill",
    answer: "were approved by the inspector",
    acceptAlso: ["were approved"],
    category: "grammar",
    level: "B2",
    section: "Passive Voice",
    points: 3,
    order: 1,
  },
  {
    question: "We are renovating the main lobby. (Passive): The main lobby ________________.",
    type: "fill",
    answer: "is being renovated",
    acceptAlso: ["is being renovated"],
    category: "grammar",
    level: "B2",
    section: "Passive Voice",
    points: 3,
    order: 2,
  },

  // Sección: Second Conditional
  {
    question: "If we ________ (have) a bigger budget, we ________ (hire) more staff.",
    type: "fill",
    answer: "had would hire",
    acceptAlso: ["had, would hire"],
    category: "grammar",
    level: "B2",
    section: "Conditionals",
    points: 3,
    order: 1,
  },

  // Sección: Reported Speech
  {
    question: 'He said: "I want the report by Friday." -> He said that ________________.',
    type: "fill",
    answer: "he wanted the report by Friday",
    acceptAlso: ["he wanted the report by Friday."],
    category: "grammar",
    level: "B2",
    section: "Reported Speech",
    points: 3,
    order: 1,
  },

  // Sección: Linking Words
  {
    question: "The project was delayed __________ the heavy rain.",
    type: "multiple",
    options: ["However", "due to", "Therefore", "Although"],
    answer: "1",
    category: "grammar",
    level: "B2",
    section: "Linking Words",
    points: 2,
    order: 1,
  },
  {
    question: "Our prices are high. __________, our quality is the best.",
    type: "multiple",
    options: ["However", "due to", "Therefore", "Although"],
    answer: "0",
    category: "grammar",
    level: "B2",
    section: "Linking Words",
    points: 2,
    order: 2,
  },

  // Sección: Phrasal Verbs
  {
    question: "Deal with (Traduce):",
    type: "fill",
    answer: "lidiar con",
    acceptAlso: ["encargarse de", "manejar"],
    category: "vocabulary",
    level: "B2",
    section: "Phrasal Verbs",
    points: 2,
    order: 1,
  },
  {
    question: "Carry out (Traduce):",
    type: "fill",
    answer: "llevar a cabo",
    acceptAlso: ["realizar", "ejecutar"],
    category: "vocabulary",
    level: "B2",
    section: "Phrasal Verbs",
    points: 2,
    order: 2,
  },
];

module.exports = allQuestions;
